package bro;

import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;

import bro.command.Command;
import bro.exception.BroException;
import bro.parser.DeadlineDetails;
import bro.parser.EventDetails;
import bro.parser.ParsedInput;
import bro.parser.Parser;
import bro.storage.Storage;
import bro.task.Deadline;
import bro.task.Event;
import bro.task.Task;
import bro.task.TaskList;
import bro.task.Todo;
import bro.ui.UserInterface;

/**
 * Main application class for the Bro chatbot.
 * Coordinates user interaction, task storage, parsing, and command execution.
 */
public class Bro {
    private static final Path DATA_FILE_PATH = Path.of("data", "bro.txt");

    private final Storage storage;
    private final UserInterface ui;
    private final TaskList tasks;

    /**
     * Constructs a Bro chatbot instance with its Storage, UserInterface, and
     * TaskList.
     */
    public Bro() {
        this.ui = new UserInterface();
        this.storage = new Storage(DATA_FILE_PATH);
        this.tasks = this.storage.load(this.ui);
    }

    /**
     * Generates the initial welcome greeting response from Bro.
     *
     * @return The welcome message string.
     */
    public String getWelcome() {
        return ui.showWelcome();
    }

    /**
     * Generates a response from the Bro chatbot based on the input and returns it.
     *
     * @param input The user input.
     * @return Response generated by the Bro chatbot.
     */
    public String getResponse(String input) {
        ParsedInput parsed = Parser.parse(input);
        return getResponse(parsed.command(), parsed.arguments());
    }

    /**
     * Generates a response using a command and arguments that have already been parsed.
     * This overload allows the CLI loop to reuse the parsed command when deciding
     * whether to stop, instead of parsing the same input twice.
     *
     * @param command   The parsed command enum constant.
     * @param arguments The parsed arguments string.
     * @return Response generated by the Bro chatbot.
     */
    private String getResponse(Command command, String arguments) {
        try {
            return executeCommand(command, arguments);
        } catch (BroException e) {
            return ui.showError(e.getMessage());
        } catch (NumberFormatException e) {
            return ui.showInvalidTaskNumberError();
        } catch (IndexOutOfBoundsException e) {
            return ui.showNoSuchTaskError();
        } finally {
            ui.showDividerWithSpacing();
        }
    }

    /**
     * Executes the parsed command with the given arguments and returns the response string.
     *
     * @param command The parsed Command enum constant.
     * @param arguments The raw arguments string for the command.
     * @return The response string to display.
     * @throws BroException If an error occurs during command execution.
     */
    private String executeCommand(Command command, String arguments) throws BroException {
        return switch (command) {
            case BYE -> ui.showGoodbye();
            case LIST -> ui.showTaskList(tasks);
            case FIND -> executeFind(arguments);
            case TASKS -> executeTasksOnDate(arguments);
            case MARK -> executeMark(arguments, true);
            case UNMARK -> executeMark(arguments, false);
            case DELETE -> executeDelete(arguments);
            case TODO -> executeAddTodo(arguments);
            case DEADLINE -> executeAddDeadline(arguments);
            case EVENT -> executeAddEvent(arguments);
            case UNKNOWN -> {
                throw new BroException("I don't get what you're trying to say bro, can you try again?");
            }
            default -> {
                // Since unhandled commands should fall into the UNKNOWN case,
                // execution should never reach this point.
                assert false : "Unhandled command type: " + command;
                throw new BroException("I don't get what you're trying to say bro, can you try again?");
            }
        };
    }

    /**
     * Executes the find command to search for tasks containing specific keywords.
     *
     * @param arguments The search keywords string.
     * @return The formatted response message containing matching tasks.
     * @throws BroException If the keywords string cannot be parsed.
     */
    private String executeFind(String arguments) throws BroException {
        String[] keywords = Parser.parseFindKeywords(arguments);
        ArrayList<Task> matchingTasks = tasks.findTasksByKeywords(keywords);
        return ui.showTasksContainingKeywords(arguments, matchingTasks);
    }

    /**
     * Executes the tasks command to query tasks occurring on a given date.
     *
     * @param arguments The date string to query.
     * @return The formatted response message containing tasks on that date.
     * @throws BroException If the date string format is invalid.
     */
    private String executeTasksOnDate(String arguments) throws BroException {
        LocalDate targetDate = Parser.parseQueryDate(arguments);
        ArrayList<Task> matchingTasks = tasks.findTasksOnDate(targetDate);
        return ui.showTasksForDate(targetDate, matchingTasks);
    }

    /**
     * Executes the mark or unmark command for a task at a given index.
     *
     * @param arguments The task index argument string.
     * @param isMark True to mark the task as done, false to mark it as not done.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the index argument cannot be parsed.
     */
    private String executeMark(String arguments, boolean isMark) throws BroException {
        int listIndex = Parser.parseTaskIndex(arguments,
                "Yo which task do you want to mark/unmark bro?");
        Task task = tasks.get(listIndex);
        String response;
        if (isMark) {
            task.markDone();
            response = ui.showTaskMarked(task);
        } else {
            task.unmarkDone();
            response = ui.showTaskUnmarked(task);
        }
        return saveAndFormatResponse(response);
    }

    /**
     * Executes the delete command to remove a task at a specified index.
     *
     * @param arguments The task index argument string.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the index argument cannot be parsed.
     */
    private String executeDelete(String arguments) throws BroException {
        int listIndex = Parser.parseTaskIndex(arguments,
                "Which task do you want to delete bro?");
        Task task = tasks.delete(listIndex);
        return saveAndFormatResponse(ui.showTaskDeleted(task, tasks.size()));
    }

    /**
     * Executes the todo command to create and add a new Todo task.
     *
     * @param arguments The todo description string.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the todo description is empty or invalid.
     */
    private String executeAddTodo(String arguments) throws BroException {
        String description = Parser.parseTodoDescription(arguments);
        Todo newTodo = new Todo(description);
        tasks.add(newTodo);
        return saveAndFormatResponse(ui.showTaskAdded(newTodo, tasks.size()));
    }

    /**
     * Executes the deadline command to create and add a new Deadline task.
     *
     * @param arguments The deadline arguments string containing description and deadline time.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the arguments are missing or malformed.
     */
    private String executeAddDeadline(String arguments) throws BroException {
        DeadlineDetails details = Parser.parseDeadlineDetails(arguments);
        Deadline newDeadline = new Deadline(details.description(), details.deadline());
        tasks.add(newDeadline);
        return saveAndFormatResponse(ui.showTaskAdded(newDeadline, tasks.size()));
    }

    /**
     * Executes the event command to create and add a new Event task.
     *
     * @param arguments The event arguments string containing description, start time, and end time.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the arguments are missing or malformed.
     */
    private String executeAddEvent(String arguments) throws BroException {
        EventDetails details = Parser.parseEventDetails(arguments);
        Event newEvent = new Event(details.description(), details.start(), details.end());
        tasks.add(newEvent);
        return saveAndFormatResponse(ui.showTaskAdded(newEvent, tasks.size()));
    }

    /**
     * Saves the current task list to storage and returns the appropriate response message.
     *
     * @param successResponse The formatted response message if saving succeeds.
     * @return The success response message, or the storage error message if saving fails.
     */
    private String saveAndFormatResponse(String successResponse) {
        String error = storage.save(tasks, ui);
        return error == null ? successResponse : error;
    }

    /**
     * Starts the main chatbot loop for the Command Line Interface (CLI) mode.
     * This method handles the input/output lifecycle required for running Bro directly
     * in the console. It is kept separately from getResponse(String), which handles
     * individual inputs for GUI clients, so the application can support both interfaces.
     */
    public void run() {
        ui.showWelcome();

        boolean isRunning = true;
        while (isRunning) {
            isRunning = processNextCommand();
        }

        ui.close();
    }

    /**
     * Reads and processes one command in the CLI loop.
     *
     * @return False when the user enters the bye command, otherwise true.
     */
    private boolean processNextCommand() {
        String input = ui.readCommand();
        ui.showLine();
        ParsedInput parsed = Parser.parse(input);
        getResponse(parsed.command(), parsed.arguments());
        return parsed.command() != Command.BYE;
    }

    /**
     * Main entry point to launch the Bro chatbot.
     *
     * @param args Command-line arguments.
     */
    public static void main(String[] args) {
        new Bro().run();
    }
}
