package bro;

import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;

import bro.command.Command;
import bro.exception.BroException;
import bro.parser.Parser;
import bro.storage.Storage;
import bro.task.Deadline;
import bro.task.Event;
import bro.task.Task;
import bro.task.TaskList;
import bro.task.Todo;
import bro.ui.UserInterface;

/**
 * Main application class for the Bro chatbot.
 * Coordinates user interaction, task storage, parsing, and command execution.
 */
public class Bro {
    private static final Path DATA_FILE_PATH = Path.of("data", "bro.txt");

    private final Storage storage;
    private final UserInterface ui;
    private final TaskList tasks;

    /**
     * Constructs a Bro chatbot instance with its Storage, UserInterface, and
     * TaskList.
     */
    public Bro() {
        this.ui = new UserInterface();
        this.storage = new Storage(DATA_FILE_PATH);
        this.tasks = this.storage.load(this.ui);
    }

    /**
     * Generates the initial welcome greeting response from Bro.
     *
     * @return The welcome message string.
     */
    public String getWelcome() {
        return ui.showWelcome();
    }

    /**
     * Generates a response from the Bro chatbot based on the input and returns it.
     *
     * @param input The user input.
     * @return Response generated by the Bro chatbot.
     */
    public String getResponse(String input) {
        try {
            Command command = Parser.parseCommand(input);
            String arguments = Parser.parseArguments(input);

            switch (command) {
                case BYE -> {
                    return ui.showGoodbye();
                }
                case LIST -> {
                    return ui.showTaskList(tasks);
                }
                case FIND -> {
                    // arguments will be the keywords to search for
                    ArrayList<Task> matchingTasks = tasks.findTasksByKeywords(arguments);
                    return ui.showTasksContainingKeywords(arguments, matchingTasks);
                }
                case TASKS -> {
                    LocalDate targetDate = Parser.parseQueryDate(arguments);
                    ArrayList<Task> matchingTasks = tasks.findTasksOnDate(targetDate);
                    return ui.showTasksForDate(targetDate, matchingTasks);
                }
                case MARK, UNMARK -> {
                    String response;
                    int listIndex = Parser.parseTaskIndex(arguments,
                            "\tYo which task do you want to mark/unmark bro?");
                    Task task = tasks.get(listIndex);
                    if (command == Command.MARK) {
                        task.markDone();
                        response = ui.showTaskMarked(task);
                    } else {
                        task.unmarkDone();
                        response = ui.showTaskUnmarked(task);
                    }
                    String error = storage.save(tasks, ui); // error should be null if saved successfully
                    return error == null ? response : error;
                }
                case DELETE -> {
                    int listIndex = Parser.parseTaskIndex(arguments,
                            "\tWhich task do you want to delete bro?");
                    Task task = tasks.delete(listIndex);
                    String error = storage.save(tasks, ui); // error should be null if saved successfully
                    String response = ui.showTaskDeleted(task, tasks.size());
                    return error == null ? response : error;
                }
                case TODO -> {
                    String description = Parser.parseTodoDescription(arguments);
                    Todo newTodo = new Todo(description);
                    tasks.add(newTodo);
                    String error = storage.save(tasks, ui); // error should be null if saved successfully
                    String response = ui.showTaskAdded(newTodo, tasks.size());
                    return error == null ? response : error;
                }
                case DEADLINE -> {
                    String[] details = Parser.parseDeadlineArguments(arguments);
                    Deadline newDeadline = new Deadline(details[0], details[1]);
                    tasks.add(newDeadline);
                    String error = storage.save(tasks, ui); // error should be null if saved successfully
                    String response = ui.showTaskAdded(newDeadline, tasks.size());
                    return error == null ? response : error;
                }
                case EVENT -> {
                    String[] details = Parser.parseEventArguments(arguments);
                    Event newEvent = new Event(details[0], details[1], details[2]);
                    tasks.add(newEvent);
                    String error = storage.save(tasks, ui); // error should be null if saved successfully
                    String response = ui.showTaskAdded(newEvent, tasks.size());
                    return error == null ? response : error;
                }
                case UNKNOWN -> {
                    throw new BroException("\tI don't get what you're trying to say bro, can you try again?");
                }
                default -> {
                    throw new BroException("\tI don't get what you're trying to say bro, can you try again?");
                }
            }
        } catch (BroException e) {
            return ui.showError(e.getMessage());
        } catch (NumberFormatException e) {
            return ui.showInvalidTaskNumberError();
        } catch (IndexOutOfBoundsException e) {
            return ui.showNoSuchTaskError();
        } finally {
            ui.showDividerWithSpacing();
        }
    }

    /**
     * Starts the main chatbot loop, reading, parsing, and executing user commands.
     */
    public void run() {
        ui.showWelcome();

        boolean isRunning = true;
        while (isRunning) {
            String input = ui.readCommand();
            ui.showLine();

            try {
                Command command = Parser.parseCommand(input);
                String arguments = Parser.parseArguments(input);

                switch (command) {
                    case BYE -> {
                        isRunning = false;
                        ui.showGoodbye();
                    }
                    case LIST -> {
                        ui.showTaskList(tasks);
                    }
                    case FIND -> {
                        // arguments will be the keywords to search for
                        ArrayList<Task> matchingTasks = tasks.findTasksByKeywords(arguments);
                        ui.showTasksContainingKeywords(arguments, matchingTasks);
                    }
                    case TASKS -> {
                        LocalDate targetDate = Parser.parseQueryDate(arguments);
                        ArrayList<Task> matchingTasks = tasks.findTasksOnDate(targetDate);
                        ui.showTasksForDate(targetDate, matchingTasks);
                    }
                    case MARK, UNMARK -> {
                        int listIndex = Parser.parseTaskIndex(arguments,
                                "\tYo which task do you want to mark/unmark bro?");
                        Task task = tasks.get(listIndex);
                        if (command == Command.MARK) {
                            task.markDone();
                            ui.showTaskMarked(task);
                        } else {
                            task.unmarkDone();
                            ui.showTaskUnmarked(task);
                        }
                        storage.save(tasks, ui);
                    }
                    case DELETE -> {
                        int listIndex = Parser.parseTaskIndex(arguments,
                                "\tWhich task do you want to delete bro?");
                        Task task = tasks.delete(listIndex);
                        storage.save(tasks, ui);
                        ui.showTaskDeleted(task, tasks.size());
                    }
                    case TODO -> {
                        String description = Parser.parseTodoDescription(arguments);
                        Todo newTodo = new Todo(description);
                        tasks.add(newTodo);
                        storage.save(tasks, ui);
                        ui.showTaskAdded(newTodo, tasks.size());
                    }
                    case DEADLINE -> {
                        String[] details = Parser.parseDeadlineArguments(arguments);
                        Deadline newDeadline = new Deadline(details[0], details[1]);
                        tasks.add(newDeadline);
                        storage.save(tasks, ui);
                        ui.showTaskAdded(newDeadline, tasks.size());
                    }
                    case EVENT -> {
                        String[] details = Parser.parseEventArguments(arguments);
                        Event newEvent = new Event(details[0], details[1], details[2]);
                        tasks.add(newEvent);
                        storage.save(tasks, ui);
                        ui.showTaskAdded(newEvent, tasks.size());
                    }
                    case UNKNOWN -> {
                        throw new BroException("\tI don't get what you're trying to say bro, can you try again?");
                    }
                    default -> {
                        throw new BroException("\tI don't get what you're trying to say bro, can you try again?");
                    }
                }
            } catch (BroException e) {
                ui.showError(e.getMessage());
            } catch (NumberFormatException e) {
                ui.showInvalidTaskNumberError();
            } catch (IndexOutOfBoundsException e) {
                ui.showNoSuchTaskError();
            } finally {
                ui.showDividerWithSpacing();
            }
        }

        ui.close();
    }

    /**
     * Main entry point to launch the Bro chatbot.
     *
     * @param args Command-line arguments.
     */
    public static void main(String[] args) {
        new Bro().run();
    }
}
