package bro;

import java.nio.file.Path;
import java.time.LocalDate;
import java.util.ArrayList;

import bro.command.Command;
import bro.exception.BroException;
import bro.parser.DeadlineDetails;
import bro.parser.EditDetails;
import bro.parser.EventDetails;
import bro.parser.ParsedInput;
import bro.parser.Parser;
import bro.storage.Storage;
import bro.task.Deadline;
import bro.task.Event;
import bro.task.Task;
import bro.task.TaskDateTime;
import bro.task.TaskList;
import bro.task.Todo;
import bro.ui.UserInterface;

/**
 * Main application class for the Bro chatbot.
 * Coordinates user interaction, task storage, parsing, and command execution.
 */
public class Bro {
    private static final Path DATA_FILE_PATH = Path.of("data", "bro.txt");

    private final Storage storage;
    private final UserInterface ui;
    private final TaskList tasks;

    /**
     * Constructs a Bro chatbot instance with its Storage, UserInterface, and
     * TaskList using the default storage file path.
     */
    public Bro() {
        this(DATA_FILE_PATH);
    }

    /**
     * Constructs a Bro chatbot instance using the specified storage file path.
     *
     * @param filePath The path to the task storage file.
     */
    public Bro(Path filePath) {
        this.ui = new UserInterface();
        this.storage = new Storage(filePath);
        this.tasks = this.storage.load(this.ui);
    }

    /**
     * Generates the initial welcome greeting response from Bro.
     *
     * @return The welcome message string.
     */
    public String getWelcome() {
        String welcome = ui.showWelcome();
        if (storage.getCorruptedLineCount() > 0) {
            welcome += String.format(
                    "\nHeads up bro, skipped %d corrupted line(s) in your save file.",
                    storage.getCorruptedLineCount());
        }
        return welcome;
    }

    /**
     * Generates a response from the Bro chatbot based on the input and returns it.
     *
     * @param input The user input.
     * @return Response generated by the Bro chatbot.
     */
    public String getResponse(String input) {
        ParsedInput parsed = Parser.parse(input);
        return getResponse(parsed.command(), parsed.arguments());
    }

    /**
     * Generates a response using a command and arguments that have already been parsed.
     * This overload allows the CLI loop to reuse the parsed command when deciding
     * whether to stop, instead of parsing the same input twice.
     *
     * @param command   The parsed command enum constant.
     * @param arguments The parsed arguments string.
     * @return Response generated by the Bro chatbot.
     */
    private String getResponse(Command command, String arguments) {
        try {
            return executeCommand(command, arguments);
        } catch (BroException e) {
            return ui.showError(e.getMessage());
        } catch (NumberFormatException e) {
            return ui.showInvalidTaskNumberError();
        } catch (IndexOutOfBoundsException e) {
            return ui.showNoSuchTaskError();
        } finally {
            ui.showDividerWithSpacing();
        }
    }

    /**
     * Executes the parsed command with the given arguments and returns the response string.
     *
     * @param command The parsed Command enum constant.
     * @param arguments The raw arguments string for the command.
     * @return The response string to display.
     * @throws BroException If an error occurs during command execution.
     */
    private String executeCommand(Command command, String arguments) throws BroException {
        return switch (command) {
            case BYE -> {
                if (!arguments.isEmpty()) {
                    throw new BroException("Bro, the 'bye' command doesn't take any extra arguments.");
                }
                yield ui.showGoodbye();
            }
            case LIST -> {
                if (!arguments.isEmpty()) {
                    throw new BroException("Bro, the 'list' command doesn't take any extra arguments.");
                }
                yield ui.showTaskList(tasks);
            }
            case FIND -> executeFind(arguments);
            case TASKS -> executeTasksOnDate(arguments);
            case MARK -> executeMark(arguments, true);
            case UNMARK -> executeMark(arguments, false);
            case DELETE -> executeDelete(arguments);
            case TODO -> executeAddTodo(arguments);
            case DEADLINE -> executeAddDeadline(arguments);
            case EVENT -> executeAddEvent(arguments);
            case EDIT -> executeEdit(arguments);
            case UNKNOWN -> {
                throw new BroException("I don't get what you're trying to say bro, can you try again?\n"
                        + "You can try stuff like: todo <desc>, deadline <desc> /by <date>, "
                        + "event <desc> /from <date> /to <date>, list, mark <num>, find <keyword>");
            }
            default -> {
                // Since unhandled commands should fall into the UNKNOWN case,
                // execution should never reach this point.
                assert false : "Unhandled command type: " + command;
                throw new BroException("I don't get what you're trying to say bro, can you try again?");
            }
        };
    }

    /**
     * Executes the find command to search for tasks containing specific keywords.
     *
     * @param arguments The search keywords string.
     * @return The formatted response message containing matching tasks.
     * @throws BroException If the keywords string cannot be parsed.
     */
    private String executeFind(String arguments) throws BroException {
        String[] keywords = Parser.parseFindKeywords(arguments);
        ArrayList<Task> matchingTasks = tasks.findTasksByKeywords(keywords);
        return ui.showTasksContainingKeywords(arguments, matchingTasks);
    }

    /**
     * Executes the tasks command to query tasks occurring on a given date.
     *
     * @param arguments The date string to query.
     * @return The formatted response message containing tasks on that date.
     * @throws BroException If the date string format is invalid.
     */
    private String executeTasksOnDate(String arguments) throws BroException {
        LocalDate targetDate = Parser.parseQueryDate(arguments);
        ArrayList<Task> matchingTasks = tasks.findTasksOnDate(targetDate);
        return ui.showTasksForDate(targetDate, matchingTasks);
    }

    /**
     * Validates that the given 0-based task index exists within the current task list.
     *
     * @param index The 0-based task index to validate.
     * @throws BroException If the index is out of bounds.
     */
    private void validateTaskIndex(int index) throws BroException {
        if (index < 0 || index >= tasks.size()) {
            if (tasks.isEmpty()) {
                throw new BroException(String.format(
                        "Bro, your list is completely empty right now, so there's no task %d.",
                        index + 1));
            } else {
                String unit = tasks.size() == 1 ? "task" : "tasks";
                throw new BroException(String.format(
                        "Bro, task %d doesn't exist. You have %d %s, so pick a number between 1 and %d.",
                        index + 1, tasks.size(), unit, tasks.size()));
            }
        }
    }

    /**
     * Executes the mark or unmark command for a task at a given index.
     *
     * @param arguments The task index argument string.
     * @param isMark    True to mark the task as done, false to mark it as not done.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the index argument cannot be parsed or is out of bounds.
     */
    private String executeMark(String arguments, boolean isMark) throws BroException {
        int listIndex = Parser.parseTaskIndex(arguments,
                "Yo which task do you want to mark/unmark bro?");
        validateTaskIndex(listIndex);
        Task task = tasks.get(listIndex);
        if (isMark) {
            if (task.isDone()) {
                return ui.showTaskAlreadyMarked(task);
            }
            task.markDone();
            String response = ui.showTaskMarked(task);
            return saveAndFormatResponse(response, () -> task.unmarkDone());
        } else {
            if (!task.isDone()) {
                return ui.showTaskAlreadyUnmarked(task);
            }
            task.unmarkDone();
            String response = ui.showTaskUnmarked(task);
            return saveAndFormatResponse(response, () -> task.markDone());
        }
    }

    /**
     * Executes the delete command to remove a task at a specified index.
     *
     * @param arguments The task index argument string.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the index argument cannot be parsed or is out of bounds.
     */
    private String executeDelete(String arguments) throws BroException {
        int listIndex = Parser.parseTaskIndex(arguments,
                "Which task do you want to delete bro?");
        validateTaskIndex(listIndex);
        Task task = tasks.delete(listIndex);
        Runnable rollback = () -> tasks.getAllTasks().add(listIndex, task);
        return saveAndFormatResponse(ui.showTaskDeleted(task, tasks.size()), rollback);
    }

    /**
     * Executes the todo command to create and add a new Todo task.
     *
     * @param arguments The todo description string.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the todo description is empty or invalid.
     */
    private String executeAddTodo(String arguments) throws BroException {
        String description = Parser.parseTodoDescription(arguments);
        Todo newTodo = new Todo(description);
        if (tasks.hasDuplicate(newTodo)) {
            Task existing = tasks.getDuplicate(newTodo);
            return ui.showDuplicateTaskWarning(existing);
        }
        tasks.add(newTodo);
        Runnable rollback = () -> tasks.delete(tasks.size() - 1);
        return saveAndFormatResponse(ui.showTaskAdded(newTodo, tasks.size()), rollback);
    }

    /**
     * Executes the deadline command to create and add a new Deadline task.
     *
     * @param arguments The deadline arguments string containing description and deadline time.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the arguments are missing or malformed.
     */
    private String executeAddDeadline(String arguments) throws BroException {
        DeadlineDetails details = Parser.parseDeadlineDetails(arguments);
        Deadline newDeadline = new Deadline(details.description(), details.deadline());
        if (tasks.hasDuplicate(newDeadline)) {
            Task existing = tasks.getDuplicate(newDeadline);
            return ui.showDuplicateTaskWarning(existing);
        }
        tasks.add(newDeadline);
        Runnable rollback = () -> tasks.delete(tasks.size() - 1);
        return saveAndFormatResponse(ui.showTaskAdded(newDeadline, tasks.size()), rollback);
    }

    /**
     * Executes the event command to create and add a new Event task.
     *
     * @param arguments The event arguments string containing description, start time, and end time.
     * @return The response message, or a storage error message if saving fails.
     * @throws BroException If the arguments are missing or malformed.
     */
    private String executeAddEvent(String arguments) throws BroException {
        EventDetails details = Parser.parseEventDetails(arguments);
        Event newEvent = new Event(details.description(), details.start(), details.end());
        if (tasks.hasDuplicate(newEvent)) {
            Task existing = tasks.getDuplicate(newEvent);
            return ui.showDuplicateTaskWarning(existing);
        }
        tasks.add(newEvent);
        Runnable rollback = () -> tasks.delete(tasks.size() - 1);
        return saveAndFormatResponse(ui.showTaskAdded(newEvent, tasks.size()), rollback);
    }

    /**
     * Executes the edit command to update fields of an existing task.
     *
     * @param arguments The raw arguments string containing task index and edit flags.
     * @return Confirmation message of the edited task, or storage error message if saving fails.
     * @throws BroException If parsing fails or field flags are invalid for the target task type.
     */
    private String executeEdit(String arguments) throws BroException {
        EditDetails details = Parser.parseEditDetails(arguments);
        validateTaskIndex(details.index());
        Task task = tasks.get(details.index());

        String prevDescription = task.getDescription();

        if (task instanceof Todo) {
            if (details.hasBy()) {
                throw new BroException("Bro, a todo task doesn't have a deadline (/by).");
            }
            if (details.hasFrom() || details.hasTo()) {
                throw new BroException("Bro, a todo task doesn't have start/end times (/from, /to).");
            }
            if (details.hasDescription()) {
                task.setDescription(details.description());
            }
        } else if (task instanceof Deadline deadline) {
            if (details.hasFrom() || details.hasTo()) {
                throw new BroException("Bro, a deadline task doesn't have start/end times (/from, /to).");
            }
            TaskDateTime newDeadline = details.hasBy() ? TaskDateTime.parse(details.by()) : null;
            TaskDateTime prevDeadline = deadline.getDeadline();
            if (details.hasDescription()) {
                deadline.setDescription(details.description());
            }
            if (newDeadline != null) {
                deadline.setDeadline(newDeadline);
            }
            if (tasks.getAllTasks().stream().anyMatch(t -> t != task && t.equals(task))) {
                deadline.setDescription(prevDescription);
                deadline.setDeadline(prevDeadline);
                throw new BroException("Bro, another task in your list already has those exact details.");
            }
            return saveAndFormatResponse(ui.showTaskEdited(task), () -> {
                deadline.setDescription(prevDescription);
                deadline.setDeadline(prevDeadline);
            });
        } else if (task instanceof Event event) {
            if (details.hasBy()) {
                throw new BroException("Bro, an event task doesn't have a deadline (/by). Use /from or /to.");
            }
            TaskDateTime newStart = details.hasFrom() ? TaskDateTime.parse(details.from()) : null;
            TaskDateTime newEnd = details.hasTo() ? TaskDateTime.parse(details.to()) : null;
            TaskDateTime finalStart = newStart != null ? newStart : event.getStart();
            TaskDateTime finalEnd = newEnd != null ? newEnd : event.getEnd();
            Event.validateChronologicalOrder(finalStart, finalEnd);

            TaskDateTime prevStart = event.getStart();
            TaskDateTime prevEnd = event.getEnd();

            if (details.hasDescription()) {
                event.setDescription(details.description());
            }
            if (newStart != null) {
                event.setStart(newStart);
            }
            if (newEnd != null) {
                event.setEnd(newEnd);
            }
            if (tasks.getAllTasks().stream().anyMatch(t -> t != task && t.equals(task))) {
                event.setDescription(prevDescription);
                event.setStart(prevStart);
                event.setEnd(prevEnd);
                throw new BroException("Bro, another task in your list already has those exact details.");
            }
            return saveAndFormatResponse(ui.showTaskEdited(task), () -> {
                event.setDescription(prevDescription);
                event.setStart(prevStart);
                event.setEnd(prevEnd);
            });
        }

        if (tasks.getAllTasks().stream().anyMatch(t -> t != task && t.equals(task))) {
            task.setDescription(prevDescription);
            throw new BroException("Bro, another task in your list already has those exact details.");
        }
        return saveAndFormatResponse(ui.showTaskEdited(task), () -> task.setDescription(prevDescription));
    }

    /**
     * Saves the current task list to storage and returns the appropriate response message.
     *
     * @param successResponse The formatted response message if saving succeeds.
     * @return The success response message, or the storage error message if saving fails.
     */
    private String saveAndFormatResponse(String successResponse) {
        return saveAndFormatResponse(successResponse, null);
    }

    /**
     * Saves the current task list to storage with an optional rollback action if saving fails.
     *
     * @param successResponse The formatted response message if saving succeeds.
     * @param rollbackAction  Action to run to revert in-memory modifications if save fails.
     * @return The success response message, or the storage error message if saving fails.
     */
    private String saveAndFormatResponse(String successResponse, Runnable rollbackAction) {
        String error = storage.save(tasks, ui);
        if (error != null) {
            if (rollbackAction != null) {
                rollbackAction.run();
            }
            return error;
        }
        return successResponse;
    }

    /**
     * Starts the main chatbot loop for the Command Line Interface (CLI) mode.
     * This method handles the input/output lifecycle required for running Bro directly
     * in the console. It is kept separately from getResponse(String), which handles
     * individual inputs for GUI clients, so the application can support both interfaces.
     */
    public void run() {
        ui.showWelcome();

        boolean isRunning = true;
        while (isRunning) {
            isRunning = processNextCommand();
        }

        ui.close();
    }

    /**
     * Reads and processes one command in the CLI loop.
     *
     * @return False when the user enters the bye command, otherwise true.
     */
    private boolean processNextCommand() {
        String input = ui.readCommand();
        ui.showLine();
        ParsedInput parsed = Parser.parse(input);
        getResponse(parsed.command(), parsed.arguments());
        return parsed.command() != Command.BYE;
    }

    /**
     * Main entry point to launch the Bro chatbot.
     *
     * @param args Command-line arguments.
     */
    public static void main(String[] args) {
        new Bro().run();
    }
}
